// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIaqX4Zd_TqBJLc_3p3o2IqYSBg_LwfEE',
    appId: '1:717526307758:web:d1aa721c65a420a1536e3f',
    messagingSenderId: '717526307758',
    projectId: 'unimarket-app-cs310',
    authDomain: 'unimarket-app-cs310.firebaseapp.com',
    storageBucket: 'unimarket-app-cs310.firebasestorage.app',
    measurementId: 'G-9WSV879BLL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHrTcXeOA5t-JHOhbfVoXQuSqOpTRi7Tw',
    appId: '1:717526307758:android:ed837516ac56ff81536e3f',
    messagingSenderId: '717526307758',
    projectId: 'unimarket-app-cs310',
    storageBucket: 'unimarket-app-cs310.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoOqHpDtbJYjZOeKuu0Pvi-QdeVsxcOw0',
    appId: '1:717526307758:ios:224d222738257aa0536e3f',
    messagingSenderId: '717526307758',
    projectId: 'unimarket-app-cs310',
    storageBucket: 'unimarket-app-cs310.firebasestorage.app',
    iosBundleId: 'com.example.reshelfAppCs310',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoOqHpDtbJYjZOeKuu0Pvi-QdeVsxcOw0',
    appId: '1:717526307758:ios:224d222738257aa0536e3f',
    messagingSenderId: '717526307758',
    projectId: 'unimarket-app-cs310',
    storageBucket: 'unimarket-app-cs310.firebasestorage.app',
    iosBundleId: 'com.example.reshelfAppCs310',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIaqX4Zd_TqBJLc_3p3o2IqYSBg_LwfEE',
    appId: '1:717526307758:web:3f2bc96271f993b2536e3f',
    messagingSenderId: '717526307758',
    projectId: 'unimarket-app-cs310',
    authDomain: 'unimarket-app-cs310.firebaseapp.com',
    storageBucket: 'unimarket-app-cs310.firebasestorage.app',
    measurementId: 'G-8Q88EGRQWC',
  );

}